### ISSUE TITLE
support environment variable expressions for docker registries?

### ISSUE THREAD

**Issue by jstrachan** [GoogleCloudPlatform/skaffold#184]
I'd like to be able to use an environment variable to describe the docker registry to use. e.g. in a `skaffold.yaml` something like:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - imageName: $MY_DOCKER_REGISTRY_SERVICE_HOST:$MY_DOCKER_REGISTRY_SERVICE_PORT/foo/bar
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
```
So processing all references to environment variables in the image name before passing it to the underlying docker commands etc.

**Comment by jstrachan** [comment]
btw my main use case for environment variables is to be able to reuse a docker registry which is deployed inside a kubernetes cluster & is only available inside the kubernetes cluster via environment variables (as you can't use kubernetes service discovery for docker registries).  Thats the default OOTB when using [Jenkins X](http://jenkins-x.io/) today. 

It'd be useful in CI / CD pipelines to be able to point at different docker registries/users based on if a build pipeline is using preview/snapshot images or real releases. Though I guess for the latter we could use separate `skaffold.yaml` files

**Comment by dgageot** [comment]
This has been fixed with https://github.com/GoogleCloudPlatform/skaffold/pull/316. @jstrachan can you confirm?

**Comment by ranginuitrot** [comment]
As it happens, I'm also working with Jenkins X, but I'd like to be able to use environment variables as docker build args (and anywhere else?). My main use case is providing a PyPi repo url with embedded credentials. Something like this would be ideal:
```yaml
apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/foo/bar:{{.VERSION}}"
  artifacts:
  - imageName: bar
    workspace: .
    docker:
      buildArgs:
        PIP_EXTRA_INDEX_URL: "{{.PIP_EXTRA_INDEX_URL}}"
```
