### ISSUE TITLE
Files in .dockerignore are still copied into context

### ISSUE THREAD

**Issue by geniass** [GoogleCloudPlatform/skaffold#203]
The .dockerignore file ensures that watchers are not setup for certain files. However these files are still copied into the build context and potentially the final image, slowing things down.

### Minimal example
.dockerignore
```
something.txt
```

Dockerfile
```
FROM alpine
COPY . /stuff
```

skaffold.yaml
```
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
    - paths:
      - k8s-*
      parameters:
        IMAGE_NAME: gcr.io/k8s-skaffold/skaffold-example

```

```shell
$ ls -a
.  ..  Dockerfile  .dockerignore  k8s-pod.yaml  main.go  skaffold-gcb.yaml  skaffold.yaml  something.txt
```

```shell
$ skaffold run
$ docker run --rm gcr.io/k8s-skaffold/skaffold-example:5ec93d2-dirty-f7ad11ab232cbbde ls -a /stuff
.
..
.dockerignore
Dockerfile
k8s-pod.yaml
main.go
skaffold-gcb.yaml
skaffold.yaml
**something.txt**

```
