### ISSUE TITLE
Could we remove duplication in skaffold.yaml?

### ISSUE THREAD

**Issue by dgageot** [GoogleCloudPlatform/skaffold#219]
I'm a bit uncomfortable in duplicating image names in the skaffold.yaml.
eg:

```
apiVersion: skaffold/v1
kind: Config

build:
  local: {}
  artifacts:
  - imageName: dgageot/petstore-ui-front
    workspace: ./ui-front
  - imageName: dgageot/petstore-ui
    workspace: ./ui

deploy:
  kubectl:
    manifests:
    - paths:
      - k8s/*.yaml
      parameters:
        IMAGE_PETSTORE_UI_FRONT: dgageot/petstore-ui-front
        IMAGE_PETSTORE_UI: dgageot/petstore-ui
```

Would it make sense to move the parameter names in the artifacts section?
Something like:

```
apiVersion: skaffold/v1
kind: Config

build:
  local: {}
  artifacts:
  - imageName: dgageot/petstore-ui-front
    workspace: ./ui-front
    property: IMAGE_PETSTORE_UI_FRONT
  - imageName: dgageot/petstore-ui
    workspace: ./ui
    property: IMAGE_PETSTORE_UI

deploy:
  kubectl:
    manifests:
    - paths:
      - k8s/*.yaml
```
