### ISSUE TITLE
Stopping and/or teardown

### ISSUE THREAD

**Issue by lgomez** [GoogleCloudPlatform/skaffold#280]
### Expected behavior
On interrupt or kill of `skaffold dev` I expected resources to be removed/stopped.

### Actual behavior
On interrupt or kill of `skaffold dev` all resources are left running.

### Information
I realize the "Expected Behavior" above may just be personal but I looked for clean ways to stop all services and resources and found nothing. Is there a way to teardown using skaffold or are we expected to use something like `kubectl delete -f ...`? It'd be nice to be able to run `skaffold stop|teardown|cleanup` or something similar. If there is a way or a convention, would you point me in the right direction?

Thank you

```
Skaffold version: v0.2.0
Operating system: Mac OS High Sierra v10.10.3
```
Content of skaffold.yaml (from https://nemethgergely.com/using-kubernetes-for-local-development/): 
```
apiVersion: skaffold/v1alpha1
kind: Config
build:
  artifacts:
  - imageName: node-app
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
    - paths:
      - k8s-app.yml
      parameters:
        IMAGE_NAME: node-app
```

### Steps to reproduce the behavior

  1. `skaffold dev`
  2. ctrl+c
  3. `kubectl get all`
