### ISSUE TITLE
Kubectl deploy does not work on multiple document YAML file

### ISSUE THREAD

**Issue by r2d4** [GoogleCloudPlatform/skaffold#303]
Skaffold can't understand multiple document YAML files yet for the kubectl deployer

```
apiVersion: v1
kind: Pod
metadata:
  name: getting-started-1
spec:
  containers:
  - name: getting-started-1
    image: gcr.io/k8s-skaffold/skaffold-example-1
---
apiVersion: v1
kind: Pod
metadata:
  name: getting-started-2
spec:
  containers:
  - name: getting-started-2
    image: gcr.io/k8s-skaffold/skaffold-example-2
```

We need to implement something like this: https://github.com/kubernetes/apimachinery/blob/master/pkg/util/yaml/decoder.go#L142-L169
