### ISSUE TITLE
tagPolicy is not parsed from config file

### ISSUE THREAD

**Issue by geniass** [GoogleCloudPlatform/skaffold#326]
### Expected behavior
Skaffold should use the tagPolicy in the config file. 
### Actual behavior
tagPolicy is not read properly, so the default value is used.
### Information

Skaffold version: v0.3.0
Operating system: Fedora 27
Content of skaffold.yaml:
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
    - k8s-*
```

The old syntax still works:
```
build:
  sha256: {}
```

Looks like the fix is changing `,inline` to `tagPolicy` [here](https://github.com/GoogleCloudPlatform/skaffold/blob/44fcb3a04ee4d0994f0d8d85f14b51798aad205f/pkg/skaffold/config/config.go#L38)
